spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/progetto_web
spring.datasource.username=root
spring.datasource.password=Password1234
spring.jpa.hibernate.ddl-auto=update